### ISSUE TITLE
LMC SQL PATCH ISSUE

### ISSUE THREAD

**Issue by DHANDAPANISATTANATHAN** [SSOMENSREPO/LMC-TS-SQL#1]
DEFECT OWNER:RL

Patch used lce table , so issue in LMC.Correct and redely immediately

**Comment by RAJALAKSHMIRAJKUMAR** [comment]
ISSUE FIXED DELIVERED IN BELOW LINK

DRIVE LINK : https://drive.google.com/a/ssomens.com/?tab=mo#folders/0Bz8XDWwyuSghUlNSYUp5amZST0k

FILE NAME : ALTER_QUERY_22042015.SQL
